apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: busybox
    imagePullPolicy: Always
    command:
    - /bin/sh
    - -c
    - while true; do sleep 30; done;
  restartPolicy: OnFailure
